version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile.server
    image: panopticon-server
    restart: always
    stdin_open: true
    tty: true

  watchman:
    build:
      dockerfile: Dockerfile.watchman
    image: panopticon-watchman
    restart: always
    stdin_open: true
    tty: true
